{
  "uid" : "4b4757e66a1912dae1a509f688f20b0f",
  "children" : [ {
    "name" : "Test defects",
    "children" : [ {
      "name" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='ehashapi.test.poolx.io', port=81): Max retries exceeded with url: /pool//v1/miner/Home (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff278a56f90>: Failed to establish a new connection: [Errno 61] Connection refused'))",
      "children" : [ {
        "name" : "test_home",
        "uid" : "ff3373a704c681b9",
        "parentUid" : "898f5196ca19e4d6e039de4fb9852752",
        "status" : "broken",
        "time" : {
          "start" : 1663321374093,
          "stop" : 1663321374148,
          "duration" : 55
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ ]
      } ],
      "uid" : "898f5196ca19e4d6e039de4fb9852752"
    } ],
    "uid" : "bdbf199525818fae7a8651db9eafe741"
  } ],
  "name" : "categories"
}